services:
  server:
    image: docker-template:1.0.0
    container_name: docker-template
    networks:
      - docker-template
    restart: on-failure
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'

networks:
  docker-template:
    name: docker-template